### ISSUE TITLE
haskell-ci: Consider adding "hooks"

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/.github#17]
Food for thought: for the sake of extensibility, does it make sense to have a notion of a "hooks" for this workflow? That is, allow users to specify shell commands to run before (i.e., a pre-hook) or after (i.e., a post-hook) the Haskell-related parts of the workflow. You could imagine something like this, inspired by [`grease`'s CI](https://github.com/GaloisInc/grease/blob/db58869d7096da9814e18a3c8f8c4955ddea304b/.github/workflows/docker.yml#L28-L30):

```yaml
    uses:
      haskell-ci:
        uses: GaloisInc/.github/workflows/haskell-ci@v1
        inputs:
          ghc: ${{ matrix.ghc }}
          os: ${{ matrix.os }}
          pre-hook: |
            sed -i 's/VERSION/0.1/' versioninfo.txt
```

_Originally posted by @RyanGlScott in https://github.com/GaloisInc/.github/pull/16#discussion_r2022964315_
