### ISSUE TITLE
Add action for downloading `what4-solvers` snapshot and adding it to the `PATH`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/.github#9]
Many `GaloisInc` projects' CI include a snippet where they download a particular [`what4-solvers`](https://github.com/GaloisInc/what4-solvers) snapshot, extract it, and add the resulting SMT solvers to the `PATH`. [Here](https://github.com/GaloisInc/cryptol/blob/15b532eec40f40a006d8579f4618f463c0794851/.github/ci.sh#L75-L82) is one such example from Cryptol:

```bash
install_system_deps() {
  (cd $BIN && curl -o bins.zip -sL "https://github.com/GaloisInc/what4-solvers/releases/download/$SOLVER_PKG_VERSION/$BIN_ZIP_FILE" && unzip -o bins.zip && rm bins.zip)
  chmod +x $BIN/*
  cp $BIN/yices_smt2$EXT $BIN/yices-smt2$EXT
  export PATH=$BIN:$PATH
  echo "$BIN" >> "$GITHUB_PATH"
  is_exe "$BIN" z3 && is_exe "$BIN" cvc4 && is_exe "$BIN" cvc5 && is_exe "$BIN" yices
}
```

Where [`SOLVER_PKG_VERSION`](https://github.com/GaloisInc/cryptol/blob/15b532eec40f40a006d8579f4618f463c0794851/.github/workflows/ci.yml#L11-L19) and [`BIN_ZIP_FILE`](https://github.com/GaloisInc/cryptol/blob/15b532eec40f40a006d8579f4618f463c0794851/.github/workflows/ci.yml#L137-L146) are defined in the YAML configuration:

```yaml
env:
  # The solver package snapshot date. If you update this, make sure to also
  # update it in the following locations:
  #
  # - Dockerfile
  # - cryptol-remote-api/Dockerfile
  # - README.md
  # - dev/dev_setup.sh
  SOLVER_PKG_VERSION: "snapshot-20250227"
```
```yaml
      - shell: bash
        run: .github/ci.sh install_system_deps
        env:
          # The full zip file name for a what4-solvers bindist. If you update
          # this, make sure to also update it in the following locations:
          #
          # - The other BIN_ZIP_FILE in the `test` job
          # - Dockerfile
          # - cryptol-remote-api/Dockerfile
          BIN_ZIP_FILE: ${{ matrix.os }}-${{ runner.arch }}-bin.zip
```

We should capture these steps in a GitHub action and package it in this repo.
